### ISSUE TITLE
mappings file request

### ISSUE THREAD

**Issue by ssyeats** [rslavin/PVDetector_Java#1]
Hello teacher, I am a student, and my research direction is mobile application privacy behavior detection. Your research is very helpful to me, but I do not know how to build an mappings file. Would you please share your achievement?Looking forward to your reply!

**Comment by rslavin** [comment]
You can find the mappings file at https://galadriel.cs.utsa.edu/~rslavin/mappings.csv and the ontology at https://galadriel.cs.utsa.edu/~rslavin/ontology.owl

**Comment by ssyeats** [comment]
> 

Thank you very much. That's so kind of you. Best wishes~
